---
- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: install dovecot
  become: true
  packages:
    name: "{{ dovecot__packages }}"
    state: "{{ dovecot__state }}"

- name: Create config directory
  become: true
  file:
    path: /etc/dovecot
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: create dovecot config
  include_tasks: templates.yml

- name: create dhparam
  become: true
  openssl_dhparam:
    path: '/etc/dovecot/dh4096.pem'
    size: 4096


