---
- name: include optional versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: install dovecot
  become: true
  ansible.builtin.package:
    name: "{{ dovecot__packages }}"
    state: "{{ dovecot__state }}"

- name: Create config directory
  become: true
  ansible.builtin.file:
    path: /etc/dovecot
    state: directory
    mode: '0755'
    owner: root
    group: root
  notify: systemctl restart dovecot

- name: create dovecot config
  ansible.builtin.include_tasks: templates.yml

- name: create dhparam
  become: true
  community.crypto.openssl_dhparam:
    path: '/etc/dovecot/dh4096.pem'
    size: 4096
  notify: systemctl restart dovecot
